### ISSUE TITLE
Upgrade to turbo 7.0.1

### ISSUE THREAD

**Issue by janmpeterka** [miguelgrinberg/turbo-flask#18]
Hi, Turbo 7.0.1 brings great changes, namely I would love to use new `after` and `before` TurboStream options.
Whats you timeframe on updating to this version? I just want to know if I should better wait with this change I'm doing or not :)

Thanks for this amazing package, allowing me to use Turbo in my Flask application!

**Comment by miguelgrinberg** [comment]
> I'm not sure I can write this implementation

Well, you could. :) Congrats and thank you so much!

**Comment by janmpeterka** [comment]
Thank you! I'm glad I could help, I really love turbo and I wouldn't be able to use it without your amazing work!
