### ISSUE TITLE
Dynamically updating highcharts with Turbo-Flask

### ISSUE THREAD

**Issue by reghardtp** [miguelgrinberg/turbo-flask#28]
Hi,

My goal is to display live data pushed from the server.
Now as far as I understand Turbo-Flask will replace/append a valid HTML string, is Turbo-Flask a good tool to then push data to the frontend to handle the update of the chart?

Is there a different tool to rather use?

Thanks!

**Comment by miguelgrinberg** [comment]
Turbo will replace the old chart with a new one, which is probably not what you want. A more efficient solution would have a JavaScript implementation in the client that receives and applies the updates on always on the same chart. You can use polling or WebSocket as a method to deliver updates to clients.

**Comment by reghardtp** [comment]
Hi, I have found a nice library that takes HTML tables and turns them into charts.
it is working well with Turbo-Flask to create a dynamically updating chart

It is called: [charts.css](https://chartscss.org/)
