### ISSUE TITLE
Multiple target

### ISSUE THREAD

**Issue by JukoiDev** [miguelgrinberg/turbo-flask#37]
How multiple target would look like for 
`turbo.push(turbo.replace(render_template('load.html', time_up=time_up, cpu=cpu, ram=ram, process_count=process_count), '???'))`

**Comment by miguelgrinberg** [comment]
Not sure if this is what you want, but you can use a list:

```python
turbo.push([
    turbo.replace(render_template(...), 'target_1'),
    turbo.replace(render_template(...), 'target_2'),
])
```

**Comment by smeetsomaiya** [comment]
I have the same issue with Gunicorn + turbo flask. 
<img width="1276" alt="Screen Shot 2022-12-12 at 1 04 56 AM" src="https://user-images.githubusercontent.com/8993207/206972099-9aa98aa6-177e-4a27-923f-8c87ecd11081.png">

This is my turbo update code

            ```
             # Runs every 2 secs in a thread
            with app.test_request_context():
                turbo.push([turbo.update(render_template('page-1-data.html'), 'page_1_svg_data'),
                            turbo.update(render_template('page-2-data.html'), 'page_2_svg_data'),
                            turbo.update(render_template('page-3-data.html'), 'page_3_svg_data')])
```
