### ISSUE TITLE
Dynamic update not working in turbo-flask 0.8.1?

### ISSUE THREAD

**Issue by andyengria** [miguelgrinberg/turbo-flask#40]
When following your blog post / guide on [Dynamically Update Your Flask Web Pages Using Turbo-Flask](https://blog.miguelgrinberg.com/post/dynamically-update-your-flask-web-pages-using-turbo-flask)
I found the dynamic update is not working with turbo-flask 0.8.1 and the example code.
It does work with 0.8.0.
Is this due to a bug in 0.8.1 or has the method of making dynamic updates work changed?

**Comment by miguelgrinberg** [comment]
Looks like the CDN that hosts the Turbo JavaScript code is having an issue with the latest version: https://github.com/hotwired/turbo/issues/735. The 0.8.0 release works fine because that loads an older version of turbo.js.

**Comment by brianm-sra** [comment]
I was also noticing this.  The load example, and my own code based on it, was working a few weeks ago, but not anymore.

**Comment by brianm-sra** [comment]
How do we specify to use the older version? Uninstall turbo-flask with pip and reinstall with a specific version number ? Modify one of the .py or .html files ?

**Comment by brianm-sra** [comment]
Or do we need to wait for the CDN issue to be resolved ?

**Comment by miguelgrinberg** [comment]
You can run `pip install turbo-flask==0.8.0` to force this version to be installed. If any other version are already installed, it will be removed first.

**Comment by brianm-sra** [comment]
Yes, that worked for me. Thank you. With 0.8.0 the dynamic updates happen in the browser.

**Comment by oliverwehrens** [comment]
It seems like the CDN url is wrong.

https://cdn.skypack.dev/pin/@hotwired/turbo@v7.2.2-RBjb2wnkmosSQVoP27jT/min/@hotwired/turbo.js
https://cdn.skypack.dev/pin/@hotwired/turbo@v7.2.0-RBjb2wnkmosSQVoP27jT/min/@hotwired/turbo.js

are working.

https://cdn.skypack.dev/pin/@hotwired/turbo@v7.2.0-jLjGyoEW3JseSmRfJh2M/min/@hotwired/turbo.js

Is not (which is in 0.8.1)

**Comment by miguelgrinberg** [comment]
The URL isn't wrong, they have just released a new version on top of the broken one. In any case, 0.8.2 is  now released with this fix. Thanks!

**Comment by oliverwehrens** [comment]
Jep, now it should work again with the 0.8.1 version I guess.
