### ISSUE TITLE
404 error on the newest version

### ISSUE THREAD

**Issue by NL-TCH** [miguelgrinberg/turbo-flask#42]
![Screenshot_20221018_202810](https://user-images.githubusercontent.com/58732773/196514210-502d5134-4aa2-45b3-8658-d5f33af5c587.png)

The function does not work and the section of the site does not refresh

**Comment by NL-TCH** [comment]
This issue does not occur when on version 0.6.1

**Comment by miguelgrinberg** [comment]
Okay, thanks. This is getting extremely annoying, I'm not sure what's going on with skypack but if their turbo URLs are not down, then they keep changing their hash.

I committed a change to switch to jsdelivr CDN now.

**Comment by miguelgrinberg** [comment]
@NL-TCH can I ask you to install the main branch and give it a try? Let me know if this works better and I'll make another official release. Thanks!

**Comment by NL-TCH** [comment]
what do you mean by main branch? this github repo branch self compiled?

**Comment by miguelgrinberg** [comment]
@NL-TCH Sorry, I should have been more clear. You can install Python packages directly from GitHub. The command you need to run is this:

    pip install git+https://github.com/miguelgrinberg/turbo-flask

**Comment by ilies-space** [comment]
@miguelgrinberg Thank you for your response, actually i did change this from 
`    {{ turbo() }}`
to 
`    {{ turbo(url= "https://cdn.skypack.dev/@hotwired/turbo") }}`

and that solved my issue without updating the package, it duo to skypack changing resources link.

**Comment by miguelgrinberg** [comment]
@ilies-space Sure, that would work too, but in general this is considered a bad practice. Not a good idea to unpin your turbo release. Whenever the turbo.js project releases a new version your application will upgrade outside of your control and without you having an opportunity to test.
