### ISSUE TITLE
Issue with turbo.push always give Failed to load resource. 

### ISSUE THREAD

**Issue by ilies-space** [miguelgrinberg/turbo-flask#43]
i'm not able to reload Html using turbo.push it give me this error from browser console:

```
https://cdn.skypack.dev/-/@hotwired/turbo@v7.2.2-RBjb2wnkmosSQVoP27jT/dist=es2020,min/@hotwired/turbo.js
Failed to load resource: the server responded with a status of 404 ()
```

**Comment by miguelgrinberg** [comment]
Duplicate of https://github.com/miguelgrinberg/turbo-flask/issues/42. Please see instructions I provided in this issue to test the fix directly off of the main branch and let me know if that addresses the problem.
