### ISSUE TITLE
Toggle Turbo Progress Bar

### ISSUE THREAD

**Issue by ererdfdfcvcv** [miguelgrinberg/turbo-flask#48]
Hey,

I am new to web application development and flask.
I am using turbo-flask for updating a loading bar and some progress messages.
So far everything works fine, but ...

a Turbo Progress Bar keeps appearing at the top of the site when running the server. I understand where the bar comes from and found the corresponding JS calls. Currently, I am hiding the bar by extending the .turbo-progress-bar CSS class with "display: none".

Is there a possibility to completely block the creation of the bar. Interestingly, the example @ _https://blog.miguelgrinberg.com/post/dynamically-update-your-flask-web-pages-using-turbo-flask_ creates no bar.
Even though my application is set up the exact same way (as far as I understood), the bar is automatically created in my app.

Greetings,
Marc

**Comment by miguelgrinberg** [comment]
Turbo-Flask just integrates turbo.js into your Flask application. If you need to customize turbo.js, then you can do so as documented by that project. See the [progress bar](https://turbo.hotwired.dev/handbook/drive#displaying-progress) documentation for help.

**Comment by ererdfdfcvcv** [comment]
Thank you for the fast reply!
The documentation gave me the hint I needed to delay/prevent the creation.

**Thanks again for the help and quick response.**
