### ISSUE TITLE
Pushing updates pile up in unfocussed tab

### ISSUE THREAD

**Issue by danricho** [miguelgrinberg/turbo-flask#52]
Hi,

I am using external triggers in my flask application to trigger turbo.push(turbo.replace(xxx)) actions.

However when my client (chrome tab) is not in focus, it isn't processed and if left out of focus long enough, the backlog can crash the browser.

What is the strategy that people use for this?

Great extension - thanks!

**Comment by miguelgrinberg** [comment]
@danricho I just released a new version of Turbo-Flask that uses hotwire turbo 8.0.5 by default.

**Comment by danricho** [comment]
Thanks very much @miguelgrinberg !
