### ISSUE TITLE
Using turbo-flask and streams with celery ?

### ISSUE THREAD

**Issue by maximelebastard** [miguelgrinberg/turbo-flask#53]
Hello there,

has anyone used turbo-flask with celery ?

I tried a few things but it seems the app instances between the worker and the webapp are separate. Anyone already made that successfully ?

**Comment by miguelgrinberg** [comment]
Unfortunately there is no easy mechanism for a process that is not the server to communicate with clients. My recommendation is that your Celery worker passes the information it wants to send to clients to the server, either through a status update or as a final result when the job is done.
